services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/ticket
      NODE_ENV: production
    env_file:
      - ./.env.development
    volumes:
      - .:/app
    command: npm run start:prod

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
